repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.42.1
    hooks:
      - id: golangci-lint
        exclude: ^(vendor|third_party)/
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.4.0
    hooks:
      - id: go-fmt
        exclude: ^(vendor|third_party)/
      - id: go-mod-tidy
        exclude: ^(vendor|third_party)/
